version: "3.3"

volumes:
  grafana-storage:

services:
  worker:
    image: tb0hdan/idun:latest
    env_file: .env
    environment:
      - CONSUL=consul
      - FREYA=${FREYA}
    restart: unless-stopped
    links:
      - consul
    depends_on:
      - consul
  consul:
    image: library/consul
    restart: unless-stopped
    ports:
      - "127.0.0.1:8500:8500"
      - "127.0.0.1:8600:8600"
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./provision/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    links:
      - worker
      - consul
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provision/idun-dashboards.json:/etc/dashboards/workers/idun-dashboard.json
      - ./provision/grafana.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./provision/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - prometheus
    links:
      - prometheus
